#!/bin/bash

# Define virtual machine names here
gpu_domains=(
    gpu
)

function gpu_begin {
    set -x

    device=$(lspci -nnD | grep "VGA compatible controller" | grep Intel)

    # Stop display manager
    systemctl stop display-manager.service

    # Unbind vtconsole
    for i in /sys/class/vtconsole/*/bind; do
        echo 0 > "$i"
    done

    # Kill pulseaudio
    killall pulseaudio

    # Unbind GPU
    echo "$device" | cut -d' ' -f1 > /sys/module/i915/drivers/pci:i915/unbind

    # Unload modules
    rmmod snd_hda_intel
    rmmod i915

    # Load vfio
    modprobe vfio-pci ids="$(echo "$device" | grep -o 8086:....)"
}

function gpu_end {
    set -x

    # Unload vfio
    rmmod vfio_pci

    # Load modules
    modprobe snd_hda_intel
    modprobe i915

    # Rebind vtconsole
    for i in /sys/class/vtconsole/*/bind; do
        echo 1 > "$i"
    done

    # Start display manager
    systemctl start display-manager.service
}

# Run only for gpu_domains
for d in "${gpu_domains[@]}"; do
    [ "$d" = "$1" ] && gpu_domain=true
done
if [ "$gpu_domain" = true ]; then
    [ "$2" = prepare ] && [ "$3" = begin ] && gpu_begin
    [ "$2" = release ] && [ "$3" = end ] && gpu_end
fi

true
